// 仮のレッスンデータ
// 本来はデータベースから取得します

export type Word = {
  id: number;
  dutch: string;
  japanese: string;
  pronunciation: string; // IPA発音記号
  exampleSentence?: string; // 例文はオプションに
};

export type LessonCategory = {
  id: string;
  title: string;
  description: string;
  words: Word[];
};

export const dummyLessons: LessonCategory[] = [
  // --- カテゴリー1: 日常生活編 ---
  {
    id: 'daily-life',
    title: '日常生活編',
    description: '毎日の生活で使えるカジュアルな表現を学びます。',
    words: [
      { id: 101, dutch: 'Hoe gaat het met je?', japanese: '調子はどう？', pronunciation: '[hu ɣaːt ət mɛt jə]' },
      { id: 102, dutch: 'Ik ga naar de winkel, wil je mee?', japanese: 'お店に行くけど、一緒に来る？', pronunciation: '[ɪk ɣaː naːr də ˈʋɪŋkəl, ʋɪl jə meː]' },
      { id: 103, dutch: 'Wat eten we vanavond?', japanese: '今夜何食べる？', pronunciation: '[ʋɑt ˈeːtə(n) ʋə vɑnˈaːvɔnt]' },
      { id: 104, dutch: 'Heb je zin in koffie?', japanese: 'コーヒー飲みたい？', pronunciation: '[hɛp jə zɪn ɪn ˈkɔfi]' },
      { id: 105, dutch: 'Het regent weer...', japanese: 'また雨だ…', pronunciation: '[hət ˈreːɣənt ʋeːr]' },
      { id: 106, dutch: 'Ik ben moe van het werk.', japanese: '仕事で疲れた。', pronunciation: '[ɪk bɛn mu vɑn ət ˈʋɛrk]' },
      { id: 107, dutch: 'Zullen we een filmpje kijken?', japanese: '映画でも見ようか？', pronunciation: '[ˈzʏlə(n) ʋə ən ˈfɪlmpjə ˈkɛikə(n)]' },
      { id: 108, dutch: 'Mijn fiets is kapot.', japanese: '自転車が壊れた。', pronunciation: '[mɛin fits ɪs kaːˈpɔt]' },
      { id: 109, dutch: 'Waar is mijn telefoon?', japanese: '携帯どこだっけ？', pronunciation: '[ʋaːr ɪs mɛin ˈteːləfoːn]' },
      { id: 110, dutch: 'Ik heb honger!', japanese: 'お腹すいた！', pronunciation: '[ɪk hɛp ˈhɔŋər]' },
      { id: 111, dutch: 'Het is zo warm vandaag.', japanese: '今日めっちゃ暑い。', pronunciation: '[hət ɪs zoː ʋɑrm vɑnˈdaːx]' },
      { id: 112, dutch: 'Kom je ook naar het feestje?', japanese: 'パーティーにも来る？', pronunciation: '[kɔm jə oːk naːr ət ˈfeːstjə]' },
      { id: 113, dutch: 'Ik ga vroeg naar bed.', japanese: '早く寝るわ。', pronunciation: '[ɪk ɣaː vrux naːr bɛt]' },
      { id: 114, dutch: 'Heb je het weekend iets leuks gedaan?', japanese: '週末何か楽しいことした？', pronunciation: '[hɛp jə ət ˈʋikɛnt its løks ɣəˈdaːn]' },
      { id: 115, dutch: 'Shit, ik ben te laat!', japanese: 'やばい、遅刻だ！', pronunciation: '[ʃɪt, ɪk bɛn tə laːt]' },
      { id: 116, dutch: 'Wacht even, ik kom eraan.', japanese: 'ちょっと待って、今行く。', pronunciation: '[ʋɑxt ˈeːvə(n), ɪk kɔm ɛrˈaːn]' },
      { id: 117, dutch: 'Leuk je weer te zien!', japanese: 'また会えて嬉しい！', pronunciation: '[løk jə ʋeːr tə zin]' },
      { id: 118, dutch: 'Ik snap er niks van.', japanese: '全然わからない。', pronunciation: '[ɪk snɑp ɛr nɪks vɑn]' },
      { id: 119, dutch: 'Zullen we naar buiten gaan?', japanese: '外に出ようか？', pronunciation: '[ˈzʏlə(n) ʋə naːr ˈbœytə(n) ɣaːn]' },
      { id: 120, dutch: 'Tot straks!', japanese: 'また後で！', pronunciation: '[tɔt strɑks]' },
      { id: 121, dutch: 'Wat ben je aan het doen?', japanese: '今なにしてるの？', pronunciation: '[ʋɑt bɛn jə aːn ət dun]' },
      { id: 122, dutch: 'Ik heb geen zin vandaag.', japanese: '今日やる気でないなー。', pronunciation: '[ɪk hɛp ɣeːn zɪn vɑnˈdaːx]' },
      { id: 123, dutch: 'Slaap lekker!', japanese: 'おやすみ！（良い睡眠を）', pronunciation: '[slaːp ˈlɛkər]' },
      { id: 124, dutch: 'Heb je een momentje?', japanese: 'ちょっと時間ある？', pronunciation: '[hɛp jə ən moːˈmɛntjə]' },
      { id: 125, dutch: 'Maakt niet uit.', japanese: '気にしないで/どっちでもいいよ。', pronunciation: '[maːkt nit œyt]' },
      { id: 126, dutch: 'Echt waar?', japanese: 'マジで？/本当に？', pronunciation: '[ɛxt ʋaːr]' },
      { id: 127, dutch: 'Geen probleem.', japanese: '問題ないよ。', pronunciation: '[ɣeːn proːˈbleːm]' },
      { id: 128, dutch: 'Ik verveel me.', japanese: '退屈だー。', pronunciation: '[ɪk vərˈveːl mə]' },
      { id: 129, dutch: 'Dat klinkt goed.', japanese: 'いいね！（Sounds good）', pronunciation: '[dɑt klɪŋkt xut]' },
      { id: 130, dutch: 'Proost!', japanese: '乾杯！', pronunciation: '[proːst]' },
    ],
  },
  // --- カテゴリー2: ニコニコ動画編 ---
  {
    id: 'niconico',
    title: 'ニコニコ動画編',
    description: 'ニコニコ文化に関するオタクな会話で使える表現。',
    words: [
      { id: 201, dutch: 'Ken je Niconico?', japanese: 'ニコニコ動画知ってる？', pronunciation: '[kɛn jə ˈnikoniko]' },
      { id: 202, dutch: 'Ik kijk graag MAD videos.', japanese: 'MAD動画を見るのが好き。', pronunciation: '[ɪk kɛik ɣraːx ɛm aː deː ˈvidijos]' },
      { id: 203, dutch: 'Die comments zijn zo grappig!', japanese: 'あのコメント超面白い！', pronunciation: '[di ˈkɔmɛnts zɛin zoː ˈɣrɑpəx]' },
      { id: 204, dutch: 'Heb je die nieuwe upload gezien?', japanese: 'あの新しいアップロード見た？', pronunciation: '[hɛp jə di ˈniʋə ˈʏploːt xəˈzin]' },
      { id: 205, dutch: 'Ik ben verslaafd aan Niconico.', japanese: 'ニコニコ動画にハマってる。', pronunciation: '[ɪk bɛn vərˈslaːft aːn ˈnikoniko]' },
      { id: 206, dutch: 'Dat liedje werd zo populair op Nico!', japanese: 'あの曲ニコニコですごく人気になったよね！', pronunciation: '[dɑt ˈlitjə ʋɛrt zoː ˌpoːpyˈlɛːr ɔp ˈniko]' },
      { id: 207, dutch: 'De danmaku zijn echt leuk.', japanese: '弾幕コメント本当に楽しい。', pronunciation: '[də ˈdɑnmaku zɛin ɛxt løk]' },
      { id: 208, dutch: 'Ik ga live kijken vanavond.', japanese: '今夜生放送見る。', pronunciation: '[ɪk ɣaː laɪf ˈkɛikə(n) vɑnˈaːvɔnt]' },
      { id: 209, dutch: 'Heb je een premium account?', japanese: 'プレミアム会員？', pronunciation: '[hɛp jə ən ˈpriːmiəm əˈkɑunt]' },
      { id: 210, dutch: 'Die video heeft zoveel views!', japanese: 'あの動画再生数すごい！', pronunciation: '[di ˈvidijo heːft ˈzoːveːl vjus]' },
      { id: 211, dutch: 'Ik kan niet stoppen met kijken.', japanese: '見るのをやめられない。', pronunciation: '[ɪk kɑn nit ˈstɔpə(n) mɛt ˈkɛikə(n)]' },
      { id: 212, dutch: 'Welke tags gebruik je meestal?', japanese: '普段どのタグ使う？', pronunciation: '[ˈʋɛlkə tægs ɣəˈbrœyk jə ˈmeːstaːl]' },
      { id: 213, dutch: 'Die mylist is echt goed.', japanese: 'そのマイリスト本当にいい。', pronunciation: '[di ˈmaɪlɪst ɪs ɛxt xut]' },
      { id: 214, dutch: 'Ik volg die uploader al jaren.', japanese: 'その投稿者何年もフォローしてる。', pronunciation: '[ɪk vɔlɣ di ˈʏploːdər ɑl ˈjaːrə(n)]' },
      { id: 215, dutch: 'Het comment-systeem is uniek.', japanese: 'コメントシステムがユニーク。', pronunciation: '[hət ˈkɔmɛnt sɪsˈteːm ɪs yˈnik]' },
      { id: 216, dutch: 'Zullen we samen een stream kijken?', japanese: '一緒に配信見ようか？', pronunciation: '[ˈzʏlə(n) ʋə ˈsaːmə(n) ən strim ˈkɛikə(n)]' },
      { id: 217, dutch: 'Die ranking verandert altijd.', japanese: 'そのランキングいつも変わる。', pronunciation: '[di ˈræŋkɪŋ vərˈɑndərt ˈɑltɛit]' },
      { id: 218, dutch: 'Ik hou van Utattemita videos.', japanese: '歌ってみた動画が好き。', pronunciation: '[ɪk hɑu vɑn yˈtɑtːemita ˈvidijos]' },
      { id: 219, dutch: 'Heb je dat meme gezien?', japanese: 'あのミーム見た？', pronunciation: '[hɛp jə dɑt mim xəˈzin]' },
      { id: 220, dutch: 'Niconico is anders dan YouTube.', japanese: 'ニコニコ動画はYouTubeとは違う。', pronunciation: '[ˈnikoniko ɪs ˈɑndərs dɑn ˈjutjup]' },
      { id: 221, dutch: 'Www草', japanese: 'www草', pronunciation: '[kusa]' },
      { id: 222, dutch: 'Die video is door de God Priester zelf gemaakt!', japanese: 'この動画は神主本人が作ったんだ！', pronunciation: '[di ˈvidijo ɪs doːr də ɣɔt ˈpristər zɛlf ɣəˈmaːkt]' },
      { id: 223, dutch: 'Tijd voor de reclame van de priester.', japanese: '神主のCMタイムだ。', pronunciation: '[tɛit voːr də rəˈklaːmə vɑn də ˈpristər]' },
      { id: 224, dutch: 'Deze "utattemita" is goddelijk.', japanese: 'この歌ってみたは神がかってる。', pronunciation: '[ˈdeːzə yˈtɑtːemita ɪs ˈɣɔdələk]' },
      { id: 225, dutch: 'Laten we de video "mylisten".', japanese: 'この動画を「マイリスト登録」しよう。', pronunciation: '[ˈlaːtə(n) ʋə də ˈvidijo ˈmaɪlɪstə(n)]' },
      { id: 226, dutch: 'De "danmaku" is te dik, ik zie niks!', japanese: '「弾幕」が厚すぎて何も見えない！', pronunciation: '[də ˈdɑnmaku ɪs tə dɪk, ɪk zi nɪks]' },
      { id: 227, dutch: 'Hij is een legendarische "utaite".', japanese: '彼は伝説の「歌い手」だ。', pronunciation: '[hɛi ɪs ən leːɣɛnˈdaːrisə yˈtaɪtə]' },
      { id: 228, dutch: 'Ik kijk altijd de "ranking".', japanese: 'いつも「ランキング」をチェックしてる。', pronunciation: '[ɪk kɛik ˈɑltɛit də ˈræŋkɪŋ]' },
      { id: 229, dutch: 'Deze choreografie is van "odottemita".', japanese: 'この振り付けは「踊ってみた」のだ。', pronunciation: '[ˈdeːzə ˌkoːre(j)oːɣraːˈfi ɪs vɑn oˈdɔtːemita]' },
      { id: 230, dutch: 'Achtentachtig reacties!', japanese: '八十八のコメントだ！', pronunciation: '[ˈɑxtəntɑxtəx reˈɑksis]' },
    ],
  },
  // --- カテゴリー3: ボーカロイド編 ---
  {
    id: 'vocaloid',
    title: 'ボーカロイド編',
    description: 'ボカロPや曲について語る時に使える表現。',
    words: [
      { id: 301, dutch: 'Miku is mijn favoriet!', japanese: 'ミクが一番好き！', pronunciation: '[ˈmiku ɪs mɛin ˌfaːvoːˈrit]' },
      { id: 302, dutch: 'Welke Vocaloid luister je graag?', japanese: 'どのボーカロイドよく聞く？', pronunciation: '[ˈʋɛlkə ˈvoːkəlɔit ˈlœystər jə ɣraːx]' },
      { id: 303, dutch: 'Die nieuwe song is zo catchy.', japanese: 'あの新曲すごくキャッチー。', pronunciation: '[di ˈniʋə sɔŋ ɪs zoː ˈkætʃi]' },
      { id: 304, dutch: 'Ik ben fan van Kenshi Yonezu.', japanese: '米津玄師のファン。', pronunciation: '[ɪk bɛn fɛn vɑn ˈkɛnʃi joːˈneːzu]' },
      { id: 305, dutch: 'Heb je Senbonzakura gehoord?', japanese: '千本桜聞いたことある？', pronunciation: '[hɛp jə ˈsɛnbonzakura ɣəˈhoːrt]' },
      { id: 306, dutch: 'Ik kan die melodie niet uit mijn hoofd krijgen.', japanese: 'そのメロディーが頭から離れない。', pronunciation: '[ɪk kɑn di ˌmeːloːˈdi nit œyt mɛin hoːft ˈkrɛiɣə(n)]' },
      { id: 307, dutch: 'Luka\'s stem is zo mooi.', japanese: 'ルカの声すごく綺麗。', pronunciation: '[ˈlukaːs stɛm ɪs zoː moːi]' },
      { id: 308, dutch: 'Die producer maakt altijd goede nummers.', japanese: 'そのプロデューサーはいつもいい曲作る。', pronunciation: '[di proːˈdjusər maːkt ˈɑltɛit ˈɣudə ˈnʏmərs]' },
      { id: 309, dutch: 'Ik ga naar een Vocaloid concert!', japanese: 'ボーカロイドコンサートに行く！', pronunciation: '[ɪk ɣaː naːr ən ˈvoːkəlɔit kɔnˈsɛrt]' },
      { id: 310, dutch: 'Rin en Len zijn zo schattig.', japanese: 'リンとレンすごく可愛い。', pronunciation: '[rɪn ɛn lɛn zɛin zoː ˈsxɑtəx]' },
      { id: 311, dutch: 'Heb je die cover gehoord?', japanese: 'そのカバー聞いた？', pronunciation: '[hɛp jə di ˈkɔvər ɣəˈhoːrt]' },
      { id: 312, dutch: 'KAITO\'s stem is zo diep.', japanese: 'KAITOの声すごく低い。', pronunciation: '[ˈkaɪtoːs stɛm ɪs zoː dip]' },
      { id: 313, dutch: 'Ik hou van elektronische muziek.', japanese: '電子音楽が好き。', pronunciation: '[ɪk hɑu vɑn ˌeːlɛkˈtroːnisə myˈzik]' },
      { id: 314, dutch: 'Die lyrics raken me echt.', japanese: 'その歌詞本当に心に響く。', pronunciation: '[di ˈlɪrɪks ˈraːkə(n) mə ɛxt]' },
      { id: 315, dutch: 'Welke tuning software gebruik je?', japanese: 'どの調声ソフト使ってる？', pronunciation: '[ˈʋɛlkə ˈtjunɪŋ ˈsɔftʋɛːr ɣəˈbrœyk jə]' },
      { id: 316, dutch: 'Ik probeer zelf ook Vocaloid muziek te maken.', japanese: '自分でもボーカロイド音楽作ろうとしてる。', pronunciation: '[ɪk proːˈbeːr zɛlf oːk ˈvoːkəlɔit myˈzik tə ˈmaːkə(n)]' },
      { id: 317, dutch: 'Die PV is zo mooi geanimeerd.', japanese: 'そのPVアニメーションがすごく綺麗。', pronunciation: '[di ˈpeːveː ɪs zoː moːi ɣəˌaːniˈmeːrt]' },
      { id: 318, dutch: 'Hatsune Miku is een icoon.', japanese: '初音ミクはアイコン的存在。', pronunciation: '[ˈhɑtsuneː ˈmiku ɪs ən iˈkoːn]' },
      { id: 319, dutch: 'Ik heb alle albums van die artiest.', japanese: 'そのアーティストのアルバム全部持ってる。', pronunciation: '[ɪk hɛp ˈɑlə ˈɑlbʏms vɑn di ɑrˈtist]' },
      { id: 320, dutch: 'Zullen we samen naar Magical Mirai gaan?', japanese: '一緒にマジカルミライに行こうか？', pronunciation: '[ˈzʏlə(n) ʋə ˈsaːmə(n) naːr ˈmædʒɪkəl ˈmiraɪ ɣaːn]' },
      { id: 321, dutch: 'Deze "tuning" is perfect.', japanese: 'この「調声」は完璧だ。', pronunciation: '[ˈdeːzə ˈtjunɪŋ ɪs pərˈfɛkt]' },
      { id: 322, dutch: 'De "Project Diva" games zijn leuk.', japanese: '「Project Diva」のゲームは楽しい。', pronunciation: '[də ˈprɔdʒɛkt ˈdiːva ɣeːms zɛin løk]' },
      { id: 323, dutch: 'Ik mis de oude Vocaloid-liedjes.', japanese: '昔のボカロ曲が恋しい。', pronunciation: '[ɪk mɪs də ˈɑudə ˈvoːkəlɔit litjəs]' },
      { id: 324, dutch: 'De "VocaDB" is een handige site.', japanese: '「VocaDB」は便利なサイトだ。', pronunciation: '[də ˈvoːkaːdeːbeː ɪs ən ˈhɑndəɣə saɪt]' },
      { id: 325, dutch: 'Hij is een meester in "fast-paced lyrics".', japanese: '彼は「早口歌詞」の達人だ。', pronunciation: '[hɛi ɪs ən ˈmeːstər ɪn fast peːst ˈlɪrɪks]' },
      { id: 326, dutch: 'Dit liedje staat in de "Hall of Legend".', japanese: 'この曲は「伝説入り」している。', pronunciation: '[dɪt ˈlitjə staːt ɪn də hɔl ɔv ˈlɛdʒənd]' },
      { id: 327, dutch: 'Ik zing graag Vocaloid-liedjes bij de karaoke.', japanese: 'カラオケでボカロ曲を歌うのが好き。', pronunciation: '[ɪk zɪŋ ɣraːx ˈvoːkəlɔit litjəs bɛi də ˌkaːraːˈoːke]' },
      { id: 328, dutch: 'Gumi\'s stem is heel realistisch.', japanese: 'Gumiの声はとてもリアル。', pronunciation: '[ˈgumiːs stɛm ɪs heːl ˌreːaːˈlɪstis]' },
      { id: 329, dutch: 'Dit liedje gaat over een donker verhaal.', japanese: 'この曲は暗い物語がテーマだ。', pronunciation: '[dɪt ˈlitjə ɣaːt ˈoːvər ən ˈdɔŋkər vərˈhaːl]' },
      { id: 330, dutch: 'De "wowaka"-stijl is uniek.', japanese: '「wowaka」スタイルはユニークだ。', pronunciation: '[də ˈwoːwaka stɛil ɪs yˈnik]' },
    ],
  },
  // --- カテゴリー4: SNS・メッセージ編 ---
  {
    id: 'sns-messaging',
    title: 'SNS・メッセージ編',
    description: 'WhatsAppやInstagramでよく使う短い表現。',
    words: [
      { id: 401, dutch: 'Gwn', japanese: 'ただ/普通に (Gewoonの略)', pronunciation: '[ɣəˈʋoːn]' },
      { id: 402, dutch: 'Wacht ff', japanese: 'ちょっと待って (Wacht evenの略)', pronunciation: '[ʋɑxt ɛf]' },
      { id: 403, dutch: 'Idd', japanese: '確かに (Inderdaadの略)', pronunciation: '[ɪndərˈdaːt]' },
      { id: 404, dutch: 'Wdj?', japanese: '何してる？ (Wat doe je?の略)', pronunciation: '[ʋɑt du jə]' },
      { id: 405, dutch: 'Gefeliciteerd!', japanese: 'おめでとう！', pronunciation: '[ɣəˌfeːlisiˈteːrt]' },
      { id: 406, dutch: 'Mooi foto!', japanese: 'いい写真！', pronunciation: '[moːi ˈfoːtoː]' },
      { id: 407, dutch: 'Lol', japanese: '(笑)', pronunciation: '[lɔl]' },
      { id: 408, dutch: 'DM me ff', japanese: 'DMして (DM me evenの略)', pronunciation: '[deː ɛm mə ɛf]' },
      { id: 409, dutch: 'Ik stuur je een tikkie.', japanese: '割り勘アプリで請求送るね。', pronunciation: '[ɪk styr jə ən ˈtɪki]' },
      { id: 410, dutch: 'Check je app.', japanese: 'WhatsApp確認して。', pronunciation: '[tʃɛk jə ɛp]' },
      { id: 411, dutch: 'Ben onderweg.', japanese: '向かってるよ。', pronunciation: '[bɛn ɔndərˈʋɛx]' },
      { id: 412, dutch: 'Laat maar.', japanese: 'もういいや。', pronunciation: '[laːt maːr]' },
      { id: 413, dutch: 'Serieus?', japanese: 'マジで？', pronunciation: '[ˌseːriˈøs]' },
      { id: 414, dutch: 'Same', japanese: '同じく/わかる', pronunciation: '[seːm]' },
      { id: 415, dutch: 'Haha, precies.', japanese: '（笑）それな。', pronunciation: '[haːhaː, prəˈsis]' },
      { id: 416, dutch: 'Stuur een update.', japanese: '近況教えて。', pronunciation: '[styr ən ˈʏpdeːt]' },
      { id: 417, dutch: 'Kk', japanese: 'おけ (Oké, okéの略)', pronunciation: '[oːˈkeː]' },
      { id: 418, dutch: 'Zeker weten!', japanese: 'もちろん！', pronunciation: '[ˈzeːkər ˈʋeːtə(n)]' },
      { id: 419, dutch: 'Lekker bezig!', japanese: 'いい感じじゃん！/やるね！', pronunciation: '[ˈlɛkər ˈbeːzəx]' },
      { id: 420, dutch: 'Xxx', japanese: 'キス（メッセージの最後）', pronunciation: '[kus kus kus]' },
    ],
  },
  // --- カテゴリー5: 恋愛・デート編 ---
  {
    id: 'dating',
    title: '恋愛・デート編',
    description: '恋愛やデートに関するカジュアルな会話表現。',
    words: [
      { id: 501, dutch: 'Heb je een vriend/vriendin?', japanese: '彼氏/彼女いる？', pronunciation: '[hɛp jə ən vrint / vrindɪn]' },
      { id: 502, dutch: 'Ik vind je leuk.', japanese: 'あなたのことが好きです。', pronunciation: '[ɪk vɪnt jə løk]' },
      { id: 503, dutch: 'Zullen we daten?', japanese: '付き合おうか？', pronunciation: '[ˈzʏlə(n) ʋə ˈdeːtə(n)]' },
      { id: 504, dutch: 'Je ziet er goed uit.', japanese: 'かっこいい/綺麗だね。', pronunciation: '[jə zit ɛr xut œyt]' },
      { id: 505, dutch: 'Wil je iets gaan drinken?', japanese: '何か飲みに行かない？', pronunciation: '[ʋɪl jə its ɣaːn ˈdrɪŋkə(n)]' },
      { id: 506, dutch: 'Ik heb een oogje op je.', japanese: '君に一目惚れしてる。', pronunciation: '[ɪk hɛp ən ˈoːxjə ɔp jə]' },
      { id: 507, dutch: 'Ben je single?', japanese: '今、恋人いないの？', pronunciation: '[bɛn jə ˈsɪŋɡəl]' },
      { id: 508, dutch: 'Wat is je type?', japanese: '好きなタイプは？', pronunciation: '[ʋɑt ɪs jə ˈtipə]' },
      { id: 509, dutch: 'We hebben een klik.', japanese: '私たち、気が合うね。', pronunciation: '[ʋə ˈhɛbə(n) ən klɪk]' },
      { id: 510, dutch: 'Mag ik je nummer?', japanese: '電話番号もらっていい？', pronunciation: '[mɑx ɪk jə ˈnʏmər]' },
      { id: 511, dutch: 'Het was een leuke date.', japanese: '楽しいデートだった。', pronunciation: '[hət ʋɑs ən ˈløkə deːt]' },
      { id: 512, dutch: 'Ik mis je.', japanese: '会いたいな/寂しいな。', pronunciation: '[ɪk mɪs jə]' },
      { id: 513, dutch: 'Laten we het rustig aan doen.', japanese: 'ゆっくり関係を進めよう。', pronunciation: '[ˈlaːtə(n) ʋə ət ˈrʏstəx aːn dun]' },
      { id: 514, dutch: 'Hij/zij is aan het flirten.', japanese: '彼/彼女、口説いてるよ。', pronunciation: '[hɛi/zɛi ɪs aːn ət ˈflɜrtə(n)]' },
      { id: 515, dutch: 'We zijn gewoon vrienden.', japanese: '私たちはただの友達だよ。', pronunciation: '[ʋə zɛin ɣəˈʋoːn ˈvrində(n)]' },
      { id: 516, dutch: 'Het is uit tussen ons.', japanese: '私たち、別れたんだ。', pronunciation: '[hət ɪs œyt ˈtʏsən ɔns]' },
      { id: 517, dutch: 'Ik ben gek op jou.', japanese: '君に夢中だよ。', pronunciation: '[ɪk bɛn ɣɛk ɔp jɑu]' },
      { id: 518, dutch: 'Zullen we samenwonen?', japanese: '一緒に住まない？', pronunciation: '[ˈzʏlə(n) ʋə ˈsaːmə(n)ʋoːnə(n)]' },
      { id: 519, dutch: 'Je bent mijn alles.', japanese: '君は僕/私の全てだ。', pronunciation: '[jə bɛnt mɛin ˈɑləs]' },
      { id: 520, dutch: 'Scharrel', japanese: '友達以上恋人未満の関係（セフレ含む）', pronunciation: '[ˈsxɑrəl]' },
    ],
  },
   // --- カテゴリー6: 学生生活編 ---
   {
    id: 'student-life',
    title: '学生生活編',
    description: '学校や勉強、友達とのことなど。',
    words: [
      { id: 601, dutch: 'Ik heb morgen een tentamen.', japanese: '明日テストがあるんだ。', pronunciation: '[ɪk hɛp ˈmɔrɣə(n) ən tɛnˈtaːmə(n)]' },
      { id: 602, dutch: 'Heb je je huiswerk al gemaakt?', japanese: 'もう宿題やった？', pronunciation: '[hɛp jə jə ˈhœysʋɛrk ɑl ɣəˈmaːkt]' },
      { id: 603, dutch: 'Ik heb een onvoldoende gehaald.', japanese: '赤点を取っちゃった。', pronunciation: '[ɪk hɛp ən ˌɔnvɔlˈdundə ɣəˈhaːlt]' },
      { id: 604, dutch: 'Zullen we in de bieb studeren?', japanese: '図書館で勉強しない？ (bieb=bibliotheek)', pronunciation: '[ˈzʏlə(n) ʋə ɪn də bip styˈdeːrə(n)]' },
      { id: 605, dutch: 'Deze les is zo saai.', japanese: 'この授業、超つまんない。', pronunciation: '[ˈdeːzə lɛs ɪs zoː saːi]' },
      { id: 606, dutch: 'Ik ga spijbelen.', japanese: 'サボるわ。', pronunciation: '[ɪk ɣaː ˈspɛibələ(n)]' },
      { id: 607, dutch: 'Wat studeer je?', japanese: '何を専攻してるの？', pronunciation: '[ʋɑt styˈdeːr jə]' },
      { id: 608, dutch: 'Ik moet een presentatie geven.', japanese: 'プレゼンしなきゃいけないんだ。', pronunciation: '[ɪk mut ən ˌpreːzɛnˈtaːsi ˈɣeːvə(n)]' },
      { id: 609, dutch: 'De leraar is best streng.', japanese: '先生、結構厳しいよね。', pronunciation: '[də ˈleːraːr ɪs bɛst strɛŋ]' },
      { id: 610, dutch: 'Heb je aantekeningen voor me?', japanese: 'ノート見せてくれない？', pronunciation: '[hɛp jə ˈaːnteːkənɪŋə(n) voːr mə]' },
      { id: 611, dutch: 'Eindelijk vakantie!', japanese: 'やっと休みだ！', pronunciation: '[ˈɛindələk vɑˈkɑnsi]' },
      { id: 612, dutch: 'Ik ben geslaagd!', japanese: '試験に合格した！', pronunciation: '[ɪk bɛn ɣəˈslaːxt]' },
      { id: 613, dutch: 'Zullen we na school wat gaan doen?', japanese: '放課後、何かしない？', pronunciation: '[ˈzʏlə(n) ʋə naː sxoːl ʋɑt ɣaːn dun]' },
      { id: 614, dutch: 'Ik zit in een tussenjaar.', japanese: '今ギャップイヤーなんだ。（高校卒業後などの猶予期間）', pronunciation: '[ɪk zɪt ɪn ən ˈtʏsə(n)jaːr]' },
      { id: 615, dutch: 'Ik heb een KNV\'tje.', japanese: '「Kut, niet voorbereid」（クソ、準備してない）の略。テスト前の決まり文句。', pronunciation: '[kaː ɛn veː tjə]' },
      { id: 616, dutch: 'De collegezaal is vol.', japanese: '講義室がいっぱいだ。', pronunciation: '[də kɔˈleːʒəzaːl ɪs vɔl]' },
      { id: 617, dutch: 'Ik ga op kamers.', japanese: '一人暮らしを始めるんだ。', pronunciation: '[ɪk ɣaː ɔp ˈkaːmərs]' },
      { id: 618, dutch: 'Heb je stufi?', japanese: '奨学金もらってる？ (studiefinancieringの略)', pronunciation: '[hɛp jə ˈstyfi]' },
      { id: 619, dutch: 'Dit is mijn scriptie.', japanese: 'これが私の卒論。', pronunciation: '[dɪt ɪs mɛin ˈskrɪpsi]' },
      { id: 620, dutch: 'Afgestudeerd!', japanese: '卒業した！', pronunciation: '[ˈɑfxəstydeːrt]' },
    ],
  },
   // --- カテゴリー7: 趣味・エンタメ編 ---
  {
    id: 'hobbies-entertainment',
    title: '趣味・エンタメ編',
    description: '好きなことやエンタメについて話す表現。',
    words: [
      { id: 701, dutch: 'Wat zijn je hobby\'s?', japanese: '趣味は何？', pronunciation: '[ʋɑt zɛin jə ˈhɔbis]' },
      { id: 702, dutch: 'Ik game graag.', japanese: 'ゲームするのが好き。', pronunciation: '[ɪk ɣeːm ɣraːx]' },
      { id: 703, dutch: 'Welke serie kijk je nu?', japanese: '今どのドラマ/アニメ見てる？', pronunciation: '[ˈʋɛlkə ˈseːri kɛik jə ny]' },
      { id: 704, dutch: 'Ik ben een enorme anime-fan.', japanese: '私、すごいアニメオタクなんだ。', pronunciation: '[ɪk bɛn ən eːˈnɔrmə ˈaːnimeː fɛn]' },
      { id: 705, dutch: 'Laten we naar de film gaan.', japanese: '映画に行こうよ。', pronunciation: '[ˈlaːtə(n) ʋə naːr də fɪlm ɣaːn]' },
      { id: 706, dutch: 'Ik lees veel manga.', japanese: 'よく漫画を読むよ。', pronunciation: '[ɪk leːs veːl ˈmɑŋɣa]' },
      { id: 707, dutch: 'Heb je de laatste aflevering gezien?', japanese: '最新話、見た？', pronunciation: '[hɛp jə də ˈlaːtstə ˈɑfleːvərɪŋ xəˈzin]' },
      { id: 708, dutch: 'Geen spoilers!', japanese: 'ネタバレしないで！', pronunciation: '[ɣeːn ˈspɔilərs]' },
      { id: 709, dutch: 'Deze band is geweldig.', japanese: 'このバンド最高だよ。', pronunciation: '[ˈdeːzə bɛnt ɪs ɣəˈʋɛldəx]' },
      { id: 710, dutch: 'Wat voor muziek luister je?', japanese: 'どんな音楽聞くの？', pronunciation: '[ʋɑt voːr myˈzik ˈlœystər jə]' },
      { id: 711, dutch: 'Ik ga dit weekend naar een festival.', japanese: '今週末、フェスに行くんだ。', pronunciation: '[ɪk ɣaː dɪt ˈʋikɛnt naːr ən ˈfɛstivɑl]' },
      { id: 712, dutch: 'Zullen we samen online gamen?', japanese: '一緒にオンラインゲームしない？', pronunciation: '[ˈzʏlə(n) ʋə ˈsaːmə(n) ˈɔnlaɪn ˈɣeːmə(n)]' },
      { id: 713, dutch: 'Mijn favoriete personage is...', japanese: '私の推しキャラは…。', pronunciation: '[mɛin ˌfaːvoːˈritə pɛrsoːˈnaːʒə ɪs]' },
      { id: 714, dutch: 'Die film was een beetje teleurstellend.', japanese: 'あの映画はちょっと期待外れだったな。', pronunciation: '[di fɪlm ʋɑs əm ˈbeːtjə ˌteːlərˈstɛlənt]' },
      { id: 715, dutch: 'Ik kan goed tekenen.', japanese: '絵を描くの得意だよ。', pronunciation: '[ɪk kɑn xut ˈteːkənə(n)]' },
      { id: 716, dutch: 'Speel je een instrument?', japanese: '何か楽器弾ける？', pronunciation: '[speːl jə ən ɪnstryˈmɛnt]' },
      { id: 717, dutch: 'Ik ben een "foodie".', japanese: '私、食べ歩きが趣味なんだ。', pronunciation: '[ɪk bɛn ən ˈfuːdi]' },
      { id: 718, dutch: 'Laten we naar de karaoke gaan!', japanese: 'カラオケ行こうよ！', pronunciation: '[ˈlaːtə(n) ʋə naːr də ˌkaːraːˈoːke ɣaːn]' },
      { id: 719, dutch: 'Ik verzamel "merch".', japanese: 'グッズ集めてるんだ。', pronunciation: '[ɪk vərˈzaːməl mɜːrtʃ]' },
      { id: 720, dutch: 'De "seiyuu" is geweldig.', japanese: '声優が素晴らしい。', pronunciation: '[də ˈsɛiyuː ɪs ɣəˈʋɛldəx]' },
    ],
  },
  // --- カテゴリー8: 感情表現編 ---
  {
    id: 'emotions',
    title: '感情表現編',
    description: '喜怒哀楽を豊かに伝えるための言葉。',
    words: [
      { id: 801, dutch: 'Ik ben zo blij!', japanese: 'めっちゃ嬉しい！', pronunciation: '[ɪk bɛn zoː blɛi]' },
      { id: 802, dutch: 'Wat geweldig!', japanese: 'なんて素晴らしいの！', pronunciation: '[ʋɑt ɣəˈʋɛldəx]' },
      { id: 803, dutch: 'Ik ben echt boos.', japanese: 'マジで怒ってるんだけど。', pronunciation: '[ɪk bɛn ɛxt boːs]' },
      { id: 804, dutch: 'Laat me met rust!', japanese: 'ほっといて！', pronunciation: '[laːt mə mɛt rʏst]' },
      { id: 805, dutch: 'Ik ben een beetje verdrietig.', japanese: 'ちょっと悲しいな。', pronunciation: '[ɪk bɛn əm ˈbeːtjə vərˈdritəx]' },
      { id: 806, dutch: 'Het kan me niet schelen.', japanese: 'どうでもいいよ。', pronunciation: '[hət kɑn mə nit ˈsxeːlə(n)]' },
      { id: 807, dutch: 'Wat een verrassing!', japanese: 'なんてサプライズ！', pronunciation: '[ʋɑt ən vərˈɑsɪŋ]' },
      { id: 808, dutch: 'Ik ben geschokt.', japanese: 'ショックだ…。', pronunciation: '[ɪk bɛn ɣəˈsxɔkt]' },
      { id: 809, dutch: 'Ik voel me zo opgelucht.', japanese: 'めっちゃホッとした。', pronunciation: '[ɪk vul mə zoː ˈɔpxəlʏxt]' },
      { id: 810, dutch: 'Ik ben zenuwachtig.', japanese: '緊張する…。', pronunciation: '[ɪk bɛn ˈzeːnyʋɑxtəx]' },
      { id: 811, dutch: 'Ik ben jaloers!', japanese: 'うらやましい！', pronunciation: '[ɪk bɛn jaːˈluːrs]' },
      { id: 812, dutch: 'Wat schattig!', japanese: '何これ、かわいい！', pronunciation: '[ʋɑt ˈsxɑtəx]' },
      { id: 813, dutch: 'Ik ben teleurgesteld.', japanese: 'がっかりだよ。', pronunciation: '[ɪk bɛn ˌteːlərɣəˈstɛlt]' },
      { id: 814, dutch: 'Ik heb er zin in!', japanese: '楽しみ！', pronunciation: '[ɪk hɛp ɛr zɪn ɪn]' },
      { id: 815, dutch: 'Ik maak me zorgen.', japanese: '心配だな…。', pronunciation: '[ɪk maːk mə ˈzɔrɣə(n)]' },
      { id: 816, dutch: 'Wat genant!', japanese: 'めっちゃ恥ずかしい！', pronunciation: '[ʋɑt ʒəˈnɑnt]' },
      { id: 817, dutch: 'Ik ben trots op je.', japanese: '君を誇りに思うよ。', pronunciation: '[ɪk bɛn trɔts ɔp jə]' },
      { id: 818, dutch: 'Ik voel me eenzaam.', japanese: '寂しいな。', pronunciation: '[ɪk vul mə ˈeːnzaːm]' },
      { id: 819, dutch: 'Ik verheug me erop.', japanese: 'それを楽しみにしてるよ。', pronunciation: '[ɪk vərˈhøːx mə ɛrˈɔp]' },
      { id: 820, dutch: 'Ik baal ervan.', japanese: 'マジ最悪。/ついてない。 (balen)', pronunciation: '[ɪk baːl ɛrˈvɑn]' },
    ],
  },
];

